Use feature(const_fn_trait_bound) instead of feature(const_fn)
    error[E0658]: trait bounds other than `Sized` on const fn parameters are unstable
      --> test_suite/tests/test.rs:105:30
        |
    105 |     const fn const_generics4<T: T1<A1 = S1<1, { 2 + 1 }>>, const C: usize>() -> S1<C, { C }> {
        |                              ^
        |
        = note: see issue #57563 <https://github.com/rust-lang/rust/issues/57563> for more information
        = help: add `#![feature(const_fn_trait_bound)]` to the crate attributes to enable